### ISSUE TITLE
Error: wrong number of arguments for 'BattleShip.constructor', expected 9 but got 7

### ISSUE THREAD

**Issue by dfoderick** [sCrypt-Inc/zk-battleship#6]
When I compile the battleship contract, the contract constructor has 9 parameters.
The code only gives the constructor 7 parameters.
Is the problem with the contract or the code?

```
fullcycle@dave-lg:~/zkbat/zk-battleship$ npx mocha tests/battleship.scrypttest.js


  Test sCrypt contract BattleShip In Javascript
    1) "before all" hook for "should success when player move x=1, y=1, hit=true"


  0 passing (1s)
  1 failing

  1) Test sCrypt contract BattleShip In Javascript
       "before all" hook for "should success when player move x=1, y=1, hit=true":
     Error: wrong number of arguments for 'BattleShip.constructor', expected 9 but got 7
      at ABICoder.checkArgs (node_modules/scryptlib/dist/abi.js:143:19)
      at ABICoder.encodeConstructorCall (node_modules/scryptlib/dist/abi.js:160:24)
      at new Contract (node_modules/scryptlib/dist/contract.js:447:92)
      at Context.<anonymous> (tests/battleship.scrypttest.js:44:18)
```

**Comment by zhfnjust** [comment]
FIxed: https://github.com/sCrypt-Inc/zk-battleship/commit/9a0c493616fe9c810b6ed5311aa10b933add1df8
