### ISSUE TITLE
No sCrypt compiler found

### ISSUE THREAD

**Issue by 84matte84** [sCrypt-Inc/zk-battleship#7]
Hello, I am tyring to compile/run/play with this battleship example provided in this repo but when I run the npm run setup I got the following error:

> battleship@0.1.0 setup
> sh scripts/setup-zokrates.sh

Compiling battleship.zok

Compiled code written to 'out'
Number of constraints: 6599
Performing setup...
WARNING: You are using the G16 scheme which is subject to malleability. See zokrates.github.io/toolbox/proving_schemes.html#g16-malleability for implications.
Verification key written to 'verification.key'
Proving key written to 'proving.key'
Setup completed
Exporting verifier...
Verifier exported to '../contracts/verifier.scrypt'
/home/masignor/.npm/_npx/913d8a511074ab97/node_modules/scryptlib/dist/findCompiler.js:94
    console.info(chalk_1.default.red.bold('**ERROR**') + " " + chalk_1.default.red('No sCrypt compiler found.') + "\n\n  ");
                                 ^

TypeError: Cannot read properties of undefined (reading 'red')
    at findCompiler (/home/masignor/.npm/_npx/913d8a511074ab97/node_modules/scryptlib/dist/findCompiler.js:94:34)
    at main (/home/masignor/.npm/_npx/913d8a511074ab97/node_modules/scryptlib/bin/cli.js:22:26)
    at Object.<anonymous> (/home/masignor/.npm/_npx/913d8a511074ab97/node_modules/scryptlib/bin/cli.js:76:3)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32)
    at Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Any idea how to solve it?
I am running on Ubuntu 22.04
Thanks

**Comment by 84matte84** [comment]
Solved with 

npx scryptlib download

which I believe should be somehow reported in a troubleshooting section within the README.
